### ISSUE TITLE
*/* does not match text/*

### ISSUE THREAD

**Issue by lohfu** [jshttp/accepts#18]
```
const accepts = require('accepts')

const accept = accepts({
  headers: {
    'accept': 'text/*',
  },
})

console.log(accept.types([ 'application/json', 'text/html' ])) // > text/html
console.log(accept.types([ 'application/json', '*/*' ])) // > false
```

**Comment by dougwilson** [comment]
This is because you cannot use partial types in the `.types` function (https://github.com/jshttp/accepts#typetypes):

> The types array can contain full MIME types or file extensions.

What are you trying to accomplish with the above?

**Comment by lohfu** [comment]
ah, i see.

well i want the */* to act as a catch all... essentially i want to return json if that matches the accept header, otherwise html.

https://github.com/midwest-js/responder/blob/master/index.js#L61

**Comment by dougwilson** [comment]
Would this work for your use-case? `responses[req.accepts(['json']) || '*/*]'

**Comment by lohfu** [comment]
now that i know i am using it wrong i was planning on implementing something like that, yes. thanks for your quick answers!

**Comment by dougwilson** [comment]
No problem!
